package models;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class IotContainer {
    //this variable is used to keep the upper and lower bounds for the values sent by the command centre
    private Integer[] commandCentreBounds = new Integer[2];

    //this variable is used to keep all the values that the IoT devices are called with by the specific IoT device
    private Map<String,Integer[]> iotBounds = new HashMap<>();

    //this variable is used to store the upper and lower bounds of the output generated by the IoT device
    private Integer[] outputBounds = new Integer[2];


    public Integer[] getCommandCentreBounds() {
        return commandCentreBounds;
    }

    public Map<String, Integer[]> getIotBounds() {
        return iotBounds;
    }

    public Integer[] getOutputBounds() {
        return outputBounds;
    }

    public void setCommandCentreBounds(Integer[] commandCentreBounds) {
        this.commandCentreBounds = commandCentreBounds;
    }

    public void setIotBounds(Map<String,Integer[]> iotBounds) {
        this.iotBounds = iotBounds;
    }

    public void setOutputBounds(Integer[] outputBounds) {
        this.outputBounds = outputBounds;
    }
}
